### ISSUE TITLE
How to Generate Training Data from URDF

### ISSUE THREAD

**Issue by qiaojunyu** [PKU-EPIC/GAPartNet#1]
Dear haoran,

Firstly, I want to express my appreciation for open-sourcing the URDF files in your GAPartNet. 
I am interested in reproducing your work and would like to replicate the results you have achieved. In order to do so, I would need access to the code or any instructions necessary to generate the training data from the URDF files. Therefore, I kindly request your assistance in providing the code or guidelines to generate the training data from the URDF files.
Thank you for your attention, and I look forward to your response.

Best regards

**Comment by geng-haoran** [comment]
Hi, Due to the limit of google drive, we currently release our urdf and render code. I provided our rendered data through PKU Drive just now, you can fill out [this form](https://forms.gle/vuh1MARH2hKQy6wU6) to get access to it! Thank you for being interested in our work!
