### ISSUE TITLE
How to calculate the Results of Part Pose Estimation?

### ISSUE THREAD

**Issue by ShaneHuangHZ** [PKU-EPIC/GAPartNet#10]
Thanks for your remarkable work!
I looked up the project, but couldn't find the code to calculate the Results of Part Pose Estimation shown in your paper. If it's my negligence, please tell me where the code is.
<img width="656" alt="image" src="https://github.com/PKU-EPIC/GAPartNet/assets/52568951/0327fc63-a4cd-4501-92f3-1100b1f19417">

Looking forward to your reply.

Regards

**Comment by yyxisgreat** [comment]
I have the same problem.So, have you find this part?

**Comment by 0Ishtar0** [comment]
I also have the same problem.So, have you find this part?
