### ISSUE TITLE
Seeking Whole Object Pose Labels

### ISSUE THREAD

**Issue by Zirconium233** [PKU-EPIC/GAPartNet#11]
The dataset lacks pose labels for each `.pth` file corresponding to objects. One of my tasks requires translating all instances of the same object to a consistent coordinate system. However, I've noticed that in all `npcs_maps`, points with instance labels of $-100$ or semantic labels of 0 are assigned a value of 0. Consequently, the main body of the object lacks valid npcs labels, hindering my ability to calculate the pose of the entire object. I'm seeking assistance in addressing this issue.

**Comment by geng-haoran** [comment]
A quick response: you can get everything from the original annotation and rendering code. See this [demo code](https://github.com/PKU-EPIC/GAPartNet/blob/release/demo.ipynb) for more details. Basicly, we annotate the bbox of each part in the default qpos. We also provide bbox calculation code [here](https://github.com/PKU-EPIC/GAPartNet/blob/release/manipulation/run.py#L215). I can also provide more details later, but for your convenience I gave this short response quickly.

**Comment by Zirconium233** [comment]
Thank you for your quick response. My dataset was inherited from another group member who omitted the `partnetMobility` folder as it was unnecessary for their purposes.  Although the issue is a misunderstand, I still appreciate your swift reply and the provided demo code.
