### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by sufubao** [PKU-EPIC/GAPartNet#14]
How to convert the data into the format you mentioned in the gapartnet/data/README.md? The format of the data I downloaded from the Google Drive you provided is different from this.

**Comment by chengyzhao** [comment]
Hi! Sorry for the late. The scripts in `dataset/render_tools` can be used to render the dataset we provided, and the script in `dataset/process_tools/convert_rendered_into_input.py` can be used to further convert the rendered data into the format we mentioned in `gapartnet/data/README.md`.
