### ISSUE TITLE
Request for GAPartNet_All Data

### ISSUE THREAD

**Issue by MingfeiShiMS** [PKU-EPIC/GAPartNet#17]
Dear haoran,

Firstly, I want to express great appreciation to your impressive work of GAPartNet. And I am interested in articulated object pose detection and your work will help me to achieve it. I have signed in the google forms but have not received the data link. I look forward to your response.

Best regards, Mingfei

**Comment by geng-haoran** [comment]
Thank you for your interest! You can find the data link at the end of the google form.
