### ISSUE TITLE
Does the author would like to release an BaiduYun? In our platform, the Peking Cloud is hard to download the full filles. Besides, the training code seems not to be released?

### ISSUE THREAD

**Issue by siaoliu** [PKU-EPIC/GAPartNet#2]
Thank you for such an excellent work !!!
Would the author be willing to release the dataset through Baidu Cloud Disk? In many scenarios, Peking University Cloud Disk often interrupts downloading, we have no idea about the reason why in three devices.
Additionally, we noticed that the training code seems to have not been fully completed yet, and we hope the author can supplement this part.

**Comment by geng-haoran** [comment]
Thanks for the feedback, the download will be very slow without the VPN of Peking University. I'll find a better way as soon as possible!

**Comment by geng-haoran** [comment]
Just updated the download link, and the speed has been tested, much faster than before. Please fill out the download form and download again.

**Comment by geng-haoran** [comment]
The training code has been released using the user-friendly PyTorch Lightning framework.
