### ISSUE TITLE
Articulation Object image Generation 

### ISSUE THREAD

**Issue by FeiiYin** [PKU-EPIC/GAPartNet#4]
Hi, Thanks for your awesome work.
Since GAPartNet dataset is built on SAPIEN, I would like to ask about how to synthesize data (e.g. image format) of articulation objects using of various states using the original urdf file. (i.e., Before rotation and after rotation)
However, I have not found any clue from the documentation of SAPEIN.

Can you provide several tips or pseudo codes to insight me?
That will be very helpful to me! Thanks in advance.

**Comment by geng-haoran** [comment]
Hi, thank you for your interest and appreciation of our work. We provide user-customized rendering code. See the code in the folder "dataset/render_tools/render.py". They can run easily.
