### ISSUE TITLE
Failed to obtain your dataset

### ISSUE THREAD

**Issue by lcl-git-3d** [PKU-EPIC/GAPartNet#6]
Thanks for your remarkable work!! I want to obtain your dataset,but failed.How to solve it?
![1701163974061](https://github.com/PKU-EPIC/GAPartNet/assets/125371176/eb0c5653-dc2f-4b51-8d50-9e9334dadea8)

**Comment by geng-haoran** [comment]
Fixed it! Thanks for your valuable issue!
