### ISSUE TITLE
 There is no corresponding data for AKB-48

### ISSUE THREAD

**Issue by qiaojunyu** [PKU-EPIC/GAPartNet#7]
This is excellent work. After downloading the data and extracting it, I found that inside, there is only the PartNet dataset, and there is no corresponding data for AKB-48.

<img width="806" alt="1704558068713" src="https://github.com/PKU-EPIC/GAPartNet/assets/33534141/13fe5af6-dbcc-4d60-b477-89cbc8bade11">

**Comment by chengyzhao** [comment]
Hi. Sorry the download link for the dataset is outdated. We have just updated the link and please check the form for the latest link https://forms.gle/3qzv8z5vP2BT5ARN7, where both the PartNet-Mobility part and the AKB-48 part can be downloaded.
