### ISSUE TITLE
Robot policies for executing the object manipulation

### ISSUE THREAD

**Issue by sjauhri** [PKU-EPIC/GAPartNet#9]
Hello team,

Do you also plan to release the code used for the heuristic interaction policies used in the robot experiments in the paper?
I'm just looking for the general simulation code to interact with objects in the dataset with a robot gripper.

**Comment by geng-haoran** [comment]
Updated, See [here](https://github.com/PKU-EPIC/GAPartNet/tree/release/manipulation) for more details.
